{
 "title": "AppSRE Overview",
 "time": { "from": "now-28d", "to": "now" },
 "templating": {
  "list": [
   { "name": "slo_datasource", "label": "SLO datasource", "query": "postgres" }
  ]
 },
 "panels": [
  { "title": "app-interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "columns": [
      { "selector": "name", "text": "name", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "data.data",
     "source": "url",
     "summarizeExpression": "count(name)",
     "type": "graphql",
     "url": "https://app-interface.devshift.net/graphql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{\n  data: apps_v1 {\n    name\n  }\n}",
      "body_type": "graphql",
      "data": "",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "columns": [
      { "selector": "name", "text": "name", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "data.data",
     "source": "url",
     "summarizeExpression": "count(name)",
     "type": "graphql",
     "url": "https://app-interface.devshift.net/graphql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{\n  data: clusters_v1 {\n    name\n  }\n}",
      "body_type": "graphql",
      "data": "",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "columns": [
      { "selector": "name", "text": "name", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "data.data",
     "source": "url",
     "summarizeExpression": "count(name)",
     "type": "graphql",
     "url": "https://app-interface.devshift.net/graphql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{\n  data: namespaces_v1 {\n    name\n  }\n}",
      "body_type": "graphql",
      "data": "",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "columns": [
      { "selector": "name", "text": "name", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "data.data",
     "source": "url",
     "summarizeExpression": "count(name)",
     "type": "graphql",
     "url": "https://app-interface.devshift.net/graphql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{\n  data: users_v1 {\n    name\n  }\n}",
      "body_type": "graphql",
      "data": "",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "AWS Accounts",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "columns": [
      { "selector": "name", "text": "name", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "data.data",
     "source": "url",
     "summarizeExpression": "count(name)",
     "type": "graphql",
     "url": "https://app-interface.devshift.net/graphql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{\n  data: awsaccounts_v1 {\n    name\n  }\n}",
      "body_type": "graphql",
      "data": "",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Slack usergroups",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "columns": [
      { "selector": "name", "text": "name", "type": "string" },
      { "selector": "service", "text": "service", "type": "string" }
     ],
     "filterExpression": "service == \"slack-usergroup\"",
     "parser": "backend",
     "root_selector": "data.data",
     "source": "url",
     "summarizeExpression": "count(name)",
     "type": "graphql",
     "url": "https://app-interface.devshift.net/graphql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{\n  data: permissions_v1 {\n    name\n    service\n  }\n}",
      "body_type": "graphql",
      "data": "",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "OCM organizations",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "targets": [
    {
     "columns": [
      { "selector": "name", "text": "name", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "data.data",
     "source": "url",
     "summarizeExpression": "count(name)",
     "type": "graphql",
     "url": "https://app-interface.devshift.net/graphql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{\n  data: ocm_instances_v1 {\n    name\n  }\n}",
      "body_type": "graphql",
      "data": "",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Glitchtip projects",
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "columns": [
      { "selector": "name", "text": "name", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "data.data",
     "source": "url",
     "summarizeExpression": "count(name)",
     "type": "graphql",
     "url": "https://app-interface.devshift.net/graphql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{\n  data: glitchtip_projects_v1 {\n    name\n  }\n}",
      "body_type": "graphql",
      "data": "",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Number of merge requests merged",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(increase(qontract_reconcile_merged_merge_requests_total{project_id=\"13582\"}[24h]))",
     "legendFormat": "merge requests"
    }
   ]
  },
  {
   "title": "Merge requests merged in <1 hour",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(qontract_reconcile_time_to_merge_merge_request_minutes_bucket{project_id=\"13582\", le=\"60.0\"}[24h])) / sum(increase(qontract_reconcile_time_to_merge_merge_request_minutes_bucket{project_id=\"13582\", le=\"+Inf\"}[24h])) * 100",
     "legendFormat": "merge requests"
    }
   ]
  },
  {
   "title": "Number of deployments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"deployment_time\",'24h'),\n  count(*) as all\nFROM deployments\nWHERE $__timeFilter(\"deployment_time\")\nGROUP BY time\nORDER BY time\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"deployment_time\",'24h'),\n  count(*) as production\nFROM deployments\nWHERE $__timeFilter(\"deployment_time\") AND env_name like '%production%'\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Cluster versions (AUS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "count by (current_version) (aus_cluster_upgrade_policy_info{current_version!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tenant SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Tenant SLO achievement for previous month",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(case when serviceslo.target > serviceslo.value then 1 else 0 end) as missed, sum(case when serviceslo.target <= serviceslo.value then 1 else 0 end) as achieved\nFROM cluster, namespace, service, serviceslo, slitype, slodoc\nWHERE serviceslo.slitype_id = slitype.id\n  AND serviceslo.slodoc_id = slodoc.id\n  AND serviceslo.service_id = service.id\n  AND serviceslo.namespace_id = namespace.id\n  AND namespace.cluster_id = cluster.id\n  AND serviceslo.token_id = (\n        SELECT distinct(token.id)\n        FROM token, latesttokens, serviceslo\n        WHERE token.id = latesttokens.token_id\n        AND token.data_type = 'SLODataType'\n        AND serviceslo.token_id = token.id\n  );"
    }
   ]
  },
  {
   "title": "Tenant Missed SLOs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT service.name as service_name, serviceslo.name as slo_name, serviceslo.target as target_slo, serviceslo.value as observed_value\nFROM cluster, namespace, service, serviceslo, slitype, slodoc\nWHERE serviceslo.slitype_id = slitype.id\n  AND serviceslo.slodoc_id = slodoc.id\n  AND serviceslo.service_id = service.id\n  AND serviceslo.namespace_id = namespace.id\n  AND namespace.cluster_id = cluster.id\n  AND serviceslo.token_id = (\n        SELECT distinct(token.id)\n        FROM token, latesttokens, serviceslo\n        WHERE token.id = latesttokens.token_id\n        AND token.data_type = 'SLODataType'\n        AND serviceslo.token_id = token.id\n  )\n  AND serviceslo.target > serviceslo.value;"
    }
   ]
  }
 ]
}